services:
  postgres:
    image: docker.io/library/postgres:17-alpine
    container_name: studyweb-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: docker.io/library/redis:8-alpine
    container_name: studyweb-redis
    ports:
      - "${REDIS_PORT}:6379"
    command: redis-server --appendonly yes

volumes:
  postgres_data:
