auth_enabled: ${LOKI_AUTH_ENABLED}

server:
  http_listen_port: ${LOKI_HTTP_PORT}
  log_level: "${LOKI_LOG_LEVEL}"

common:
  path_prefix: "${LOKI_PATH_PREFIX}"
  replication_factor: ${LOKI_REPLICATION_FACTOR}
  ring:
    instance_addr: "${LOKI_INSTANCE_ADDR}"
    kvstore:
      store: "${LOKI_RING_KVSTORE}"

storage_config:
  use_thanos_objstore: true
  object_store:
    s3:
      bucket_name: "${S3_BUCKET}"
      endpoint: "${STORAGE_HOST_ENDPOINT}"
      region: "${S3_REGION}"
      access_key_id: "${S3_ACCESS_KEY}"
      secret_access_key: "${S3_SECRET_KEY}"
      insecure: ${S3_INSECURE}

schema_config:
  configs:
    - from: "${LOKI_SCHEMA_START_DATE}"
      store: "${LOKI_STORE_TYPE}"
      object_store: "${LOKI_OBJECT_STORE}"
      schema: "${LOKI_SCHEMA_VERSION}"
      index:
        prefix: "${LOKI_INDEX_PREFIX}"
        period: "${LOKI_INDEX_PERIOD}"

query_range:
  results_cache:
    cache:
      redis:
        endpoint: studyweb-redis:6379
        expiration: "${LOKI_REDIS_EXPIRATION:-1h}"

compactor:
  working_directory: "${LOKI_COMPACTOR_WORKING_DIR}"

ingester:
  wal:
    flush_on_shutdown: ${LOKI_INGESTER_WAL_FLUSH_ON_SHUTDOWN}

limits_config:
  max_query_length: ${LOKI_MAX_QUERY_LENGTH}
