spring:
  datasource:
    url: jdbc:postgresql://${DATABASE_SERVER:studyweb-postgres}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  flyway:
    enabled: false
logging:
  loki:
    url: ${LOKI_URL}
  file:
    name: logs/backend.log
  logback:
    rollingpolicy:
      max-file-size: 10MB       
      max-history: 7

s3:
  endpoint: ${S3_URL:}
  access-key: ${S3_ACCESS_KEY}
  secret-key: ${S3_SECRET_KEY}
  bucket: ${S3_BUCKET}
  region: ${S3_REGION:ap-southeast-1}
  max-size-document-upload: ${MAX_SIZE_DOCUMENT_UPLOAD:104857600}
  max-size-avatar-upload: ${MAX_SIZE_AVATAR_UPLOAD:20971520}