package studyweb.cus.enums;

public enum ActionType {
  LOGIN,
  LOGOUT,
  REGISTER,
  SUBMIT_ASSESSMENT,
  UPDATE_PROFILE, // CURRENTLY REDUNDANT
  REQUEST_VIP,
  CREATE_LESSON,
  UPDATE_LESSON,
  DELETE_LESSON,
  CREATE_ASSESSMENT,
  UPDATE_ASSESSMENT,
  DELETE_ASSESSMENT,
}
