name: Study Web Backend CD flow

on:
  workflow_run:
    workflows: ["Study Web Backend CI flow"]
    types:
      - completed
    branches:
      - main
      - staging

concurrency:
  group: be-deploy
  cancel-in-progress: false

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}/backend
  GITOPS_REPO: CUS-Study-Web/study-web-gitops

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted

    steps:
      - name: Checkout GitOps Manifests
        uses: actions/checkout@v4
        with:
          repository: ${{ env.GITOPS_REPO }}
          path: gitops-manifests
          ref: main
      - name: Verify Podman user
        run: |
          whoami
          id
          podman info --format 'rootless={{.Host.Security.Rootless}}'
      - name: Create backend.env from secret
        env:
          BACKEND_ENV_CONTENT: ${{ secrets.BACKEND_ENV_FILE }}
        run: |
          printf "%s" "$BACKEND_ENV_CONTENT" > gitops-manifests/backend.env

      - name: Deploy Backend
        env:
          BACKEND_IMAGE: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        working-directory: gitops-manifests
        run: |
          if [ "${{ github.event.workflow_run.head_branch }}" = "main" ]; then
            IMAGE_NAME="$BACKEND_IMAGE:${{ github.event.workflow_run.head_sha }}" make be
          elif [ "${{ github.event.workflow_run.head_branch }}" = "staging" ]; then
            IMAGE_NAME="$BACKEND_IMAGE:github.event.workflow_run.head_branch" make be
          else
            echo "Unsupported branch: ${{ github.event.workflow_run.head_branch }}"
            exit 1
          fi