name: Validate if Staging PR

on:
  pull_request:
    branches:
      - main

env:
  TARGET_BRANCH: main
  ALLOWED_SOURCE_BRANCH: staging

jobs:
  validate-source:
    runs-on: ubuntu-latest

    steps:
      - name: Check source branch
        run: |
          echo "Source branch: ${{ github.head_ref }}"
          echo "Target branch: ${{ github.base_ref }}"

          if [ "${{ github.head_ref }}" != "${{ env.ALLOWED_SOURCE_BRANCH }}" ]; then
            echo "Only '${{ env.ALLOWED_SOURCE_BRANCH }}' can be merged into '${{ env.TARGET_BRANCH }}'."
            exit 1
          fi

          echo "Valid: ${{ env.ALLOWED_SOURCE_BRANCH }} -> ${{ env.TARGET_BRANCH }}"